name: Cleanup SWA Environments

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete SWA environment
        uses: azure/cli@v1
        with:
          inlineScript: >
            az staticwebapp environment delete --name BI-Website --environment-name pr-${{ github.event.pull_request.number }} --resource-group BI-Website-RG --yes
